version: '2'
services:
  backend:
    image: ptothep/server:latest
    ports:
      - '3333:3333'
    restart: always
    volumes:
      - /sys:/sys
    depends_on:
      - mqtt
  mqtt:
    restart: always
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  temp_collector:
    image: ptothep/temp:latest
    restart: always
    depends_on:
      - mqtt
    volumes:
      - /sys/bus/w1/devices:/sys/bus/w1/devices
networks:
  default:
    external:
      name: pool
