version: '2'
services:
  frontend:
    image: ptothep/frontend:latest
    networks:
      - pool
    ports:
      - '80:80'
    depends_on:
      - backend
  backend:
    image: ptothep/server:latest
    networks:
      - pool
    depends_on:
      - gpio
      - mqtt
  gpio:
    image: ptothep/gpio:latest
    networks:
      - pool
    depends_on:
      - mqtt
    volumes:
      - /sys:/sys

  mqtt:
    image: eclipse-mosquitto
    networks:
      - pool

networks:
  pool:
    external:
      name: pool
