version: '2'
services:
  influxdb:
    image: arm32v7/influxdb
    restart: always
    volumes:
      - /mnt/disk1/influxdb:/var/lib/influxdb
  chronograf:
    image: arm32v7/chronograf
    restart: always
    entrypoint: chronograf --influxdb-url="http://influxdb:8086"
    ports:
      - 8888:8888
    depends_on:
      - influxdb
  telegraf:
    image: arm32v7/telegraf
    volumes:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
  temp_collector:
    image: ptothep/temp:latest
    depends_on:
      - influxdb
    volumes:
      - /sys/bus/w1/devices:/sys/bus/w1/devices
networks:
  default:
    external:
      name: influxdb
