version: '2'
services:
  influxdb:
    image: arm32v7/influxdb
    restart: always
    volumes:
      - /mnt/disk1/influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    volumes:
      - /mnt/disk1/grafana:/var/lib/grafana
  telegraf:
    image: arm32v7/telegraf
    restart: always
    volumes:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
  mqtt:
    restart: always
    image: eclipse-mosquitto
    ports:
      - 1883:1883
  temp_collector:
    image: ptothep/temp:latest
    restart: always
    depends_on:
      - influxdb
    volumes:
      - /sys/bus/w1/devices:/sys/bus/w1/devices
networks:
  default:
    external:
      name: influxdb
