version: '2'
services:
  influxdb:
    image: influxdb:alpine
    restart: always
  chronograf:
    image: chronograf:alpine
    restart: always
    entrypoint: chronograf --influxdb-url="http://influxdb:8086"
    ports:
      - 8888:8888
    depends_on:
      - influxdb
  telegraf:
    image: telegraf:alpine
    volumes:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
networks:
  default:
    external:
      name: influxdb
